server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/agoncal/spring-petclinic-microservices-config
          username: agoncal
          password: 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
          default-label: main
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
        native:
          searchLocations: file:///${GIT_REPO}

